# Sharpmake AppVeyor CI configuration

image: Visual Studio 2015

version: 0.0.{build}

platform:
 - Any CPU

configuration:
 - Debug
 - Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '1.0.{build}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
 - cmd: dotnet restore

build:
  project: Sharpmake.sln
  verbosity: minimal

after_build:
  - cmd: 7z a Sharpmake_%CONFIGURATION%.zip %APPVEYOR_BUILD_FOLDER%\Sharpmake.Application\bin\%CONFIGURATION%\*

after_test:
 - cmd: python regression_test.py

artifacts:
  - path: Sharpmake_Release.zip
    name: Sharpmake
    type: zip
  - path: Sharpmake_Debug.zip
    name: Sharpmake_Debug
    type: zip
