# Sharpmake AppVeyor CI configuration

image: Visual Studio 2015

version: 0.1.{build}

platform:
 - Any CPU

configuration:
 - Debug
 - Release

branches:
  only:
    - master
    - dev

assembly_info:
  patch: true
  file: 'Sharpmake**\AssemblyInfo.*'
  assembly_version: '1.0.{build}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

install:
  - nuget install ILMerge -ExcludeVersion -OutputDirectory %APPVEYOR_BUILD_FOLDER%

before_build:
 - cmd: dotnet restore

build:
  project: Sharpmake.sln
  verbosity: minimal

after_build:
  - cmd: python deploy_binaries.py -c %CONFIGURATION%
  - cmd: echo Running ILMerge && %APPVEYOR_BUILD_FOLDER%\ILMerge\tools\ilmerge.exe /out:Sharpmake.exe /ndebug /wildcards Binaries\Sharpmake.Application.exe Binaries\Sharpmake*.dll

after_test:
 - cmd: python regression_test.py

artifacts:
  - path: Sharpmake.exe
    name: Sharpmake

deploy:
  release: Sharpmake-v$(appveyor_build_version)
  description: 'Prebuilt sharpmake for Windows'
  provider: GitHub
  auth_token:
    secure: 1vWe/XVH31N4HDjazKrGdEFBzVJu6Z7YyEZIBv+p3YNOKkywICcj/6G/D1CzWC6I
  artifact: Sharpmake
  draft: false
  prerelease: false
  on:
    configuration: release
    branch: master
    appveyor_repo_tag: true