# Sharpmake AppVeyor CI configuration

image: Visual Studio 2015

platform:
 - Any CPU

configuration:
 - Debug
 - Release

before_build:
 - cmd: dotnet restore

build:
  project: Sharpmake.sln
  verbosity: minimal

after_build:
  - cmd: 7z a Sharpmake_%CONFIGURATION%.zip %APPVEYOR_BUILD_FOLDER%\Sharpmake.Application\bin\%CONFIGURATION%\*

after_test:
 - cmd: python regression_test.py

artifacts:
  - path: Sharpmake_Release.zip
    name: Sharpmake
    type: zip
