os: Visual Studio 2015

version: 0.0.{build}

before_build:
  - cmd: git clean -ffxd
  - cmd: nuget restore Sharpmake.sln

build_script:
  - cmd: echo "Building Release:" && "%VS140COMNTOOLS%\..\IDE\devenv.com" /Build "Debug" Sharpmake.sln
  - cmd: echo "Building Debug:" && "%VS140COMNTOOLS%\..\IDE\devenv.com" /Build "Release" Sharpmake.sln

test_script:
  - cmd: nunit3-console Sharpmake.UnitTests\bin\debug\Sharpmake.UnitTests.dll --result=myresults.xml;format=AppVeyor

artifacts:
  - path: Sharpmake.Application\bin\release\*
    name: Sharpmake

deploy:
- provider: GitHub
  auth_token:
    secure: 1vWe/XVH31N4HDjazKrGdEFBzVJu6Z7YyEZIBv+p3YNOKkywICcj/6G/D1CzWC6I